FROM ubuntu:latest
RUN apt-get update && apt-get upgrade -y
CMD echo "Hello, World!"

# docker build -f ./Dockerfile -t softy-pinko:task0 .
# docker run -it --rm --name softy-pinko-task0 softy-pinko:task0
